"""add rating and review_count to highest_rated tables

Revision ID: 0535c611d98e
Revises: c8efbc09ce65
Create Date: 2021-11-21 15:16:35.730280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0535c611d98e'
down_revision = 'c8efbc09ce65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ff_highest_rated', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('ff_highest_rated', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('nl_highest_rated', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('nl_highest_rated', sa.Column('review_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nl_highest_rated', 'review_count')
    op.drop_column('nl_highest_rated', 'rating')
    op.drop_column('ff_highest_rated', 'review_count')
    op.drop_column('ff_highest_rated', 'rating')
    # ### end Alembic commands ###
