"""update tables to include gm columns

Revision ID: b453159251d8
Revises: cb56f63e945f
Create Date: 2021-09-11 16:12:00.974092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b453159251d8'
down_revision = 'cb56f63e945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ff_brand', sa.Column('gm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ff_brand', 'gm_brand', ['gm_id'], ['id'])
    op.add_column('nl_brand', sa.Column('gm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nl_brand', 'gm_brand', ['gm_id'], ['id'])
    op.add_column('wm_brand', sa.Column('gm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wm_brand', 'gm_brand', ['gm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wm_brand', type_='foreignkey')
    op.drop_column('wm_brand', 'gm_id')
    op.drop_constraint(None, 'nl_brand', type_='foreignkey')
    op.drop_column('nl_brand', 'gm_id')
    op.drop_constraint(None, 'ff_brand', type_='foreignkey')
    op.drop_column('ff_brand', 'gm_id')
    # ### end Alembic commands ###
