"""update product tables to include gm columns

Revision ID: c8efbc09ce65
Revises: b453159251d8
Create Date: 2021-09-11 16:15:22.901178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8efbc09ce65'
down_revision = 'b453159251d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ff_product', sa.Column('gm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ff_product', 'gm_product', ['gm_id'], ['id'])
    op.add_column('nl_product', sa.Column('gm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nl_product', 'gm_product', ['gm_id'], ['id'])
    op.add_column('wm_product', sa.Column('gm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wm_product', 'gm_product', ['gm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wm_product', type_='foreignkey')
    op.drop_column('wm_product', 'gm_id')
    op.drop_constraint(None, 'nl_product', type_='foreignkey')
    op.drop_column('nl_product', 'gm_id')
    op.drop_constraint(None, 'ff_product', type_='foreignkey')
    op.drop_column('ff_product', 'gm_id')
    # ### end Alembic commands ###
